org: 'orionpersonal'
app: 'hooks'
service: 'hooks'

plugins:
 - 'serverless-rust'
 - 'serverless-offline'

provider:
  name: 'aws'
  runtime: 'rust'
  environment:
    STAGE: ${opt:stage}

package:
  individually: true

custom:
  rust:
    dockerImage: 'cakekindel/lambda-rust'
    dockerTag: '0.3.0-rust-1.51.0'
  serverless-offline:
    noPrependStageInUrl: true

functions:
  hooks:
    handler: hooks_lambda
    events:
      - http:
          method: 'any'
          path: '/{any+}'
      - schedule:
          rate: 'rate(30 minutes)'
          input: {kind: 'RunJobs'}
      - schedule:
          rate: 'rate(5 minutes)'
          input: {kind: 'KeepWarm'}
